services:
- docker

language: go

go:
- "1.x"

env:
  GO111MODULE: "on"

script:
- make container-build

deploy:
  skip_cleanup: true
  provider: script
  script: bash scripts/image-push.sh
  on:
    branch: master
